import Head from 'next/head';
import styled from 'styled-components';
import Flex from '@/utils/grid/Flex';
import StackedIconButton from '@/components/StackedIconButton';
import { breakpoints } from '@/utils/constants/screens';
import { colors } from '@/utils/constants/palette';
const AfiB = '/icons/AFB.svg';
const Ortho = '/icons/ORTHO.svg';
const Vte = '/icons/VTE.svg';


const StyledStackedIconButton = styled(StackedIconButton)`
  width: 30%;
`;

const StyledFlex = styled(Flex)`

  @media(max-width: ${breakpoints.lg}px) {
    flex-direction: column;
    align-items: center;
    padding: 16px;
  }
`;

const HelpContainer = styled(Flex)`
  padding: 24px 0;

  h2 {
    text-align: center;
  }

`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Eliquis Rebuild</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <HelpContainer
          justify='center'
        >
          <h2>TELL ME ME HOW ELIQUIS CAN HELP</h2>
        </HelpContainer>
        <StyledFlex
          justify='space-between'
        >
          <StackedIconButton 
            icon={AfiB}
            highlightText={<>Reduce the Risk of Stroke Due to Nonvalvular Atrial Fibrillation (AFib)</>}
            buttonText="ELIQUIS & NONVAVULAR AFIB"
            footerText="For patients with AFib, a type of irregular heartbeat, not caused by a heart valve problem"
          />
          <StyledStackedIconButton 
            icon={Vte}
            highlightText={<>Decrease Risk of DVT Blood Clots After Hip or Knee Replacement Surgery</>}
            buttonText="ELIQUIS & HIP/KNEE REPLACEMENT"
            footerText="For patients who have had hip surgery or knee replacement surgery"
          />
          <StyledStackedIconButton 
              icon={Ortho}
              highlightText={<>Treat Blood Clots In the Veins of the Legs/Lungs & Reduce Risk of it Occuring again</>}
              buttonText="ELIQUIS & DVT/PE"
              footerText="For patients with deep vein thrombosis (DVT) or pulmonary embolism (PE)"
          />
        </StyledFlex>
    </>
  )
}